<!DOCTYPE html>
<html>
    <head>
    </head>

    <body>
Test
<?= $test ?>
<?= ($_->escapeHtml)('start & test') ?>
<?= ($_->escapeHtml)('<tag>') ?>
<?= ($_->escapeHtml)('qu"o`t\'es') ?>
        <div <?= ($_->htmlAttributes)(['style' => ['width' => 80, 'height' => '90px'], 'class' => 'Main']) ?>>
            Proba
        </div>
        <script>
        <?php $input = <<<INPUT
sta&quot;;  alert(&quot;IGotYou!&quot;); var xss=&quot;true
INPUT;
?>
            var test1 = <?= ($_->escapeJs)('any1'); ?>;
            var test2 = <?= ($_->escapeJs)('"not" know & <>'); ?>;
            var test3 = <?= ($_->escapeJs)($input); ?>;
            var test4 = <?= ($_->escapeJs)(null); ?>;

            var test5 = <?= ($_->jsVariable) ("'not' know & <>"); ?>;
            var test6 = <?= ($_->jsVariable) (null); ?>;
            var test7 = <?= ($_->jsVariable) (['a', 'b', 'c']); ?>;
            var test8 = <?= ($_->jsVariable) (['a' => '1', 'b', 'c' => 2]); ?>;
            var test9 = <?= ($_->jsVariable) ($input); ?>;
        </script>
        <?= ($_->escapeHtml)($child1 ?? '[child1]') ?>
    </body>
</html>